---
- name: Registrar agente HDPS contra CommServe
  hosts: hdps_linux_clients
  become: true
  gather_facts: true

  roles:
    - role: hdps_agent
  vars:
    hdps_run_install_and_register: false
    hdps_run_install: false
    hdps_run_register: true
    hdps_run_validate: false