---
hdps_focus: "Instance001"

hdps_install_directory: "/opt/hds"
hdps_temp_directory: "/tmp"
hdps_remote_installer_archive: "/tmp/commvault_unix_11.40.16.tar.gz"
hdps_remote_installer_dir: "/tmp/commvault_unix_installer"

hdps_register_enabled: true


hdps_components:
  - 1002
  - 1101

hdps_client_name: "{{ inventory_hostname }}"
hdps_client_hostname: "{{ ansible_fqdn | default(inventory_hostname) }}"
hdps_interface_name: "{{ ansible_default_ipv4.address | default(ansible_host) | default(inventory_hostname) }}"

hdps_auth_method: "user_password"

hdps_commserve_hostname: ""
hdps_commcell_user: ""
hdps_commcell_password: ""
hdps_authcode: ""

hdps_use_http_proxy: false
hdps_force_install: false